### ISSUE TITLE
How to include node?

### ISSUE THREAD

**Issue by cburgdorf** [emk/heroku-buildpack-rust#6]
Hi @emk,

sorry for hijacking the issue tracker for this off topic question but I was wondering if you could give me advice on how to modify the buildpack to include node? I've never created a buildpack before so I'm happy for any pointers.

Cheers,

Christoph

**Comment by emk** [comment]
The machine setup all happens here: https://github.com/emk/heroku-buildpack-rust/blob/master/bin/compile

Maybe you could use https://github.com/ddollar/heroku-buildpack-multi to run both a Node buildpack, then a Rust buildpack? It probably depends on exactly what you want.

**Comment by lancecarlson** [comment]
@emk I think you answered this question adequately by mentioning the multi buildpack. @cburgdorf just make sure to include this rust buildpack and Heroku's official node buildpack (https://github.com/heroku/heroku-buildpack-nodejs) and it should work fine. The only issue I see you running into is that the the buildpacks might get a little schizophrenic because it's looking for both a node.js app AND a rust application. Both types of projects have different requirements to get loaded/bootstrap (ie nodejs package.json file). Is your project really a mix of both a node app and a Rust app? If so, I highly suggest you take another look at your project's requirements and possibly consider splitting the applications apart into separate smaller projects. Another option is to completely get rid of the Node bits and just write everything in Rust. :100:
